### PR TITLE
update games.json with Emanuel Lasker vs Aron Nimzowitsch #95

### LINKED ISSUE #95: Emanuel Lasker vs Aron Nimzowitsch
```
[Event "St. Petersburg"]
[Site "St. Petersburg  RUE"]
[Date "1914.04.22"]
[EventDate "1914.04.21"]
[Round "2"]
[Result "1/2-1/2"]
[White "Emanuel Lasker"]
[Black "Aron Nimzowitsch"]
[ECO "B16"]
[WhiteElo "?"]
[BlackElo "?"]
[PlyCount "83"]

1. e4 { Notes by Raymond Keene. } c6 2. d4 d5 3. Nc3 dxe4
4. Nxe4 {This was another favourite of Nimzowitsch's, but he
did not like the generally quiet situations generated by the
classical 4...Bf5, preferring the tense struggles that
resulted from 4...Nf6 and after 5 Nxf6+ the recapture with the
e-pawn. Asztalos-Nimzowitsch, Bled 1931, went 5...exf6 6 c3
Bd6 7 Bd3 O-O 8 Qc2 h6 9 Ne2 Qc7 10 Be3 Nd7 11 Qd2?! Better 11
O-O-O Re8 12 g4! 11...Re8 12 Ng3? Bf4! and Nimzowitsch was
beginning to get on top.} Nf6 5. Nxf6+ gxf6 {Nimzowitsch, on
occasion, played the alternative fifth move recapture
5...gxf6. His game against Leonhardt at Carlsbad 1911, must
have been one of the first games with this idea. } 6. Be2
{Nowadays 6 c3 Bf5 7 Bc4 or 7 Ne2 would more likely be
played. } 6...Bf5 7. Bf3 Qa5+ 8. c3 h5 {!? Intending to
prevent White castling kingside. } 9. Bxh5 Nd7 10. Bg4 Bxg4
11. Qxg4 O-O-O 12. Ne2 e6 13. Bf4 Qb5 14. O-O-O Nb6 15. Ng3 {?
15 b3 would leave White with a safe though difficult game --
Lasker. } 15...Qd5 16. Kb1 Qxg2 17. Rdg1 Qxf2 18. Ne4 Qh4
19. Qf3 Nc4 20. Ka1 f5 21. Ng5 Bd6 22. Bc1 Rd7 23. Rg2 Bc7
24. Rhg1 Nd6 25. Qe2 Ne4 26. Nf3 Qh3 {26...Qh5 is probably
better. } 27. a3 a6 28. Be3 Rhd8 29. Ka2 Rh8 30. Ka1 Rhd8
31. Ka2 Re8 32. Rg8 Rxg8 33. Rxg8+ Rd8 34. Rg7 Rd7 35. Rg8+
Rd8 36. Rg7 Rf8 {Again 36...Qh5, threat 37...Bxh2. } 37. c4
Nf6 {Better 37...Kd8. } 38. Bg5 Nh5 39. Rxf7 Rxf7 40. Qxe6+
Rd7 41. Ne5 Bxe5 42.Qe8+ {Nimzowitsch should certainly have
won this game.} 1/2-1/2
```

### PR DESCRIPTION
**Pull request by mobeendev**
@programarivm  Update games.json with Emanuel Lasker vs Aron Nimzowitsch thatt closes #95

### CODE REVIEW

**Review by programarivm — CHANGES_REQUESTED** [review]
See https://github.com/chesslablab/chess-api/issues/73#issuecomment-1729128928

**Comment by mobeendev** [comment]
@programarivm I couldn't find the following file
cli/annotations.php
image

**Comment by SmashedFrenzy16** [comment]
@mobeendev, the file `cli/annotations.php` probably doesn't exist because you have to make your own PHP file with the RAV formatting contents and run it (I had to do the same).

**Comment by programarivm** [comment]
The Chess API codebase doesn't include the example script shown in https://github.com/chesslablab/chess-api/issues/73#issuecomment-1729128928

**Pull request closed without merging**
