### PR TITLE
Update games.json with Raymond Keene vs Vladimir Kovacevic game

### PR DESCRIPTION
**Pull request by SmashedFrenzy16**
Closes https://github.com/chesslablab/chess-api/issues/99

### CODE REVIEW

**Review by programarivm — CHANGES_REQUESTED** [review]
See https://github.com/chesslablab/chess-api/issues/73#issuecomment-1729128928

**Comment by SmashedFrenzy16** [comment]
@programarivm I have checked the file by clicking the edit button. The `movetext` seems to already be in the format you want it to be in.

**Comment by SmashedFrenzy16** [comment]
@programarivm can this PR now be merged?

**Comment by programarivm** [comment]
The changes requested should be committed to the PR for it to be reviewed again.

Let's recap.

- The movetext coding convention should adhere to the discussion at https://github.com/chesslablab/chess-api/issues/73

- https://github.com/chesslablab/chess-api/pull/121 shows step by step how to adhere to the convention. 

Keep it up,

**Comment by programarivm** [comment]
🙂 The movetext needs to be filtered first by using the following PHP script @SmashedFrenzy16 

```php
<?php

use Chess\Play\RavPlay;

require __DIR__  . '/../vendor/autoload.php';

$movetext = "1. Nf3 { Notes by Raymond Keene. } d5 2. b3 Bg4 3. Bb2 Nd7
4. g3 Bxf3 {A bold decision indicating that Black is playing
for a win. This was the last round and if Kovacevic could beat
me he would have tied with me.} 5. exf3 Ngf6 6. f4 e6 7. Bg2
{?! Dubious. 7 Bh3! intending the disruptive advance f4-f5 is
less stereotyped.} 7...Be7 8. O-O O-O 9. d3 a5 10. a4 c6
11. Nd2 b5 12. Qe2 bxa4 {? Now White obtains the upper
hand. It was essential for Black to maintain the tension with
moves such as ...Rb8 and ...Re8 when his position would even
be slightly preferable.} 13. Rxa4 Nb6 14. Ra2 {!} a4 15. Rfa1
axb3 16. Rxa8 Nxa8 17. Nxb3 Nb6 {Not good: White now has the
opportunity to launch a variety of favourable combinations,
but it's clear that Black's position is already far from
satisfactory (White is better developed and his well
cO-Ordinated pieces control the vital a-file and a1-h8
diagonal).} 18. f5 {! Inaugurating the combination. Black must
accept the sacrifice, otherwise (after 19 fxe6) he would shed
his e-pawn to the combined onslaught of White's pieces.}
18...exf5 19. Nd4 Qd7 20. Bh3 {! Also good was 20 Nxc6 Qxc6 21
Qxe7 but the text is more accurate. Black cannot allow the
white knight to reach f5 since the threats against g7 would be
intolerable.} 20...g6 {Or 20...Ng4 21 Nxf5!} 21. Bxf5 {!! Once
again 21 Nxc6 Qxc6 22 Qxe7 was very good, but White has
something more ambitious in mind.} 21...gxf5 22. Ra7 {!! This
move visibly came as a shock to my opponent. Black has no
choice but to fall in with White's plans.} 22...Qxa7 23. Nxc6
Qd7 {There are two major alternative defences: a) 23...Qa2 24
Nxe7+ Kg7 25 Nxf5+ Kg8 (or 25...Kg6 26 Ne7+ Kg7 27 Qg4+) 26
Qg4+ Nxg4 27 Ne7 mate. b) 23...Ba3! (Best) 24 Nxa7 (24 Bxf6
Qa4! is highly unclear) 24...Bxb2 when White has queen for
rook and two pieces, but Black's forces are rather awkwardly
placed and this enables White to increase his advantage as
follows: 25 c4! Bd4 26 Nb5 Re8! 27 Qf3 Bc5 28 d4 Bf8 29 c5 Nc4
30 Qxf5, and in view of the powerful c-pawn, Black's weakened
kingside and the scattered dispositions of the black army,
White should win. However, this was Black's only chance of
resistance. But, as so often, a combinational blow disturbs
the balance of the victim's objectivity and he fails to
discover the most tenacious defensive possibilities.}
24. Nxe7+ Kg7 25. Qh5 {! Completely unanswerable. For example:
25...Qxe7 26 Qg5+ Kh8 27 Bxf6+ picking up the other knight in
addition; or 25...h6 26 Nxf5+ or 25...Ra8 26 Qg5+ Kf8 27 Bxf6
with Qg8 mate to follow.} 1-0";

$ravPlay = (new RavPlay($movetext))->validate();

$filtered = $ravPlay->getRavMovetext()->filtered();

echo $filtered . PHP_EOL;

```

```
php cli/annotations.php 
1.Nf3 {Notes by Raymond Keene.} d5 2.b3 Bg4 3.Bb2 Nd7 4.g3 Bxf3 {A bold decision indicating that Black is playing for a win. This was the last round and if Kovacevic could beat me he would have tied with me.} 5.exf3 Ngf6 6.f4 e6 7.Bg2 {?! Dubious. 7 Bh3! intending the disruptive advance f4-f5 is less stereotyped.} 7...Be7 8.O-O O-O 9.d3 a5 10.a4 c6 11.Nd2 b5 12.Qe2 bxa4 {? Now White obtains the upper hand. It was essential for Black to maintain the tension with moves such as...Rb8 and...Re8 when his position would even be slightly preferable.} 13.Rxa4 Nb6 14.Ra2 {!} a4 15.Rfa1 axb3 16.Rxa8 Nxa8 17.Nxb3 Nb6 {Not good: White now has the opportunity to launch a variety of favourable combinations, but it's clear that Black's position is already far from satisfactory (White is better developed and his well cO-Ordinated pieces control the vital a-file and a1-h8 diagonal).} 18.f5 {! Inaugurating the combination. Black must accept the sacrifice, otherwise (after 19 fxe6) he would shed his e-pawn to the combined onslaught of White's pieces.} 18...exf5 19.Nd4 Qd7 20.Bh3 {! Also good was 20 Nxc6 Qxc6 21 Qxe7 but the text is more accurate. Black cannot allow the white knight to reach f5 since the threats against g7 would be intolerable.} 20...g6 {Or 20...Ng4 21 Nxf5!} 21.Bxf5 {!! Once again 21 Nxc6 Qxc6 22 Qxe7 was very good, but White has something more ambitious in mind.} 21...gxf5 22.Ra7 {!! This move visibly came as a shock to my opponent. Black has no choice but to fall in with White's plans.} 22...Qxa7 23.Nxc6 Qd7 {There are two major alternative defences: a) 23...Qa2 24 Nxe7+ Kg7 25 Nxf5+ Kg8 (or 25...Kg6 26 Ne7+ Kg7 27 Qg4+) 26 Qg4+ Nxg4 27 Ne7 mate. b) 23...Ba3! (Best) 24 Nxa7 (24 Bxf6 Qa4! is highly unclear) 24...Bxb2 when White has queen for rook and two pieces, but Black's forces are rather awkwardly placed and this enables White to increase his advantage as follows: 25 c4! Bd4 26 Nb5 Re8! 27 Qf3 Bc5 28 d4 Bf8 29 c5 Nc4 30 Qxf5, and in view of the powerful c-pawn, Black's weakened kingside and the scattered dispositions of the black army, White should win. However, this was Black's only chance of resistance. But, as so often, a combinational blow disturbs the balance of the victim's objectivity and he fails to discover the most tenacious defensive possibilities.} 24.Nxe7+ Kg7 25.Qh5 {! Completely unanswerable. For example: 25...Qxe7 26 Qg5+ Kh8 27 Bxf6+ picking up the other knight in addition; or 25...h6 26 Nxf5+ or 25...Ra8 26 Qg5+ Kf8 27 Bxf6 with Qg8 mate to follow.}
```
See https://github.com/chesslablab/chess-api/commit/c7b4cccb6ed878caa7396de09a79d4b88027f228

**Comment by SmashedFrenzy16** [comment]
Oh ok I see that the formatting is slightly different - I'll try and relove this with the PHP script.

**Comment by SmashedFrenzy16** [comment]
@programarivm, it's fixed now!

**Comment by programarivm** [comment]
If clicking on **Chessboard > RAV Movetext** the filtered movetext is now loaded.
 
www chesslablab com_

One next step is to use Numeric Annotation Glyphs (NAGs) as in the existing annotated games.

Happy coding!

**Review by programarivm — CHANGES_REQUESTED** [review]
See https://github.com/chesslablab/chess-api/pull/117#issuecomment-1742645768

**Comment by SmashedFrenzy16** [comment]
@programarivm how do I implement this?

**Comment by programarivm** [comment]
@SmashedFrenzy16 this is an example on using NAGs:

```
7.Bg2 {?! Dubious. 7 Bh3! intending the disruptive advance f4-f5 is less stereotyped.}
```

```
7.Bg2 $6 {Dubious. 7 Bh3! intending the disruptive advance f4-f5 is less stereotyped.}
```

Keep it up,

**Pull request closed without merging**
