### PR TITLE
Update games.json with Raymond Keene vs Andrew Jonathan Mestel

### PR DESCRIPTION
**Pull request by SmashedFrenzy16**
Fixes: https://github.com/chesslablab/chess-api/issues/116

### CODE REVIEW

**Review by programarivm — CHANGES_REQUESTED** [review]
See https://github.com/chesslablab/chess-api/pull/117#issuecomment-1742645768

**Comment by SmashedFrenzy16** [comment]
@programarivm I am trying my best to implement NAGs into this annotated chess game.

**Comment by programarivm** [comment]
Thank you @SmashedFrenzy16,

The commits in the following PR are now showing how to implement the NAGs.

- https://github.com/chesslablab/chess-api/pull/127

Remember, when [linking a PR to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) by using a keyword there's no need to link the issue to a PR.


Happy coding and learning!

**Review by aminzayer — APPROVED** [review]

**Comment by SmashedFrenzy16** [comment]
@programarivm I'll give my best attempt at implementing the NAGs.

**Pull request closed without merging**
